### PR TITLE
fix: es6 syntax get error for old browser

### PR DESCRIPTION
**Pull request by Qquanwei**

### CODE REVIEW

**Comment by alfg** [comment]
Hi @Qquanwei, have you tried using the generated file from https://github.com/alfg/ping.js/blob/master/dist/ping.js?

The file in the PR is considered a source file and will get transpiled into the `dist` folder with the `var` for older browser support.

**Comment by Qquanwei** [comment]
This dist file is es5 syntax, but I notice the package.json `main` field still is `index.js`. so webpack will pack es6 index.js into bundle.

**Comment by Qquanwei** [comment]
someing I miss. I use the npm and put `import ping from 'ping.js'` in my project. so webpack will looking for package.json main field as source file.

**Comment by alfg** [comment]
Ah, that makes sense. Thank you!

**Comment by alfg** [comment]
Published: https://www.npmjs.com/package/ping.js/v/0.2.3

**Comment by Qquanwei** [comment]
awesome

**Pull request merged**
